sudo: true

language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - tools
    - platform-tools
    - android-24
    - build-tools-24.0.2
  licenses:
    - android-sdk-preview-license-84831b94
    - android-sdk-license-8933bad1
    - android-sdk-license-.+
    - google-gdk-license-.+

before_script:
  - export PATH=$PATH:$HOME/.gradle/caches/okbuck/buck/bin

script:
  - ./gradlew assemble
  - ./buckw --version
  - buck query "kind('android_binary', '//...')" | xargs buck build

notifications:
  email: false

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/modules-2/
    - $HOME/.gradle/wrapper/